services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - pgdb
    ports:
      - 8020:8000
    entrypoint: sh /code/entrypoint.sh
    networks:
      - smotify

  pgdb:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5452:5432
    env_file: .env
    healthcheck:
      test: [ 'CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smotify

networks:
  smotify:
    name: smotify
    driver: bridge